#!/bin/bash

OUTPUT_PATH=logs
DATA_PATH=DataFiles/training_tfrecords

gcloud ml-engine local train \
    --module-name trainer.task \
    --package-path trainer/ \
    --distributed \
    -- \
    --file-dir $DATA_PATH \
    --train-steps 1 \
    --num-epochs 1 \
    --learning-rate .01 \
    --job-dir $OUTPUT_PATH \
    --verbosity INFO


________________

JOB_NAME=isles_33
BUCKET_NAME=coral-weaver-4010
OUTPUT_PATH=gs://$BUCKET_NAME/$JOB_NAME
DATA_PATH=gs://$BUCKET_NAME/data/isles_tfrecords
REGION=us-east1

gcloud ml-engine jobs submit training $JOB_NAME \
    --job-dir $OUTPUT_PATH \
    --runtime-version 1.2 \
    --module-name trainer.task \
    --package-path trainer/ \
    --region $REGION \
    --scale-tier CUSTOM \
    --config config.yaml \
    -- \
    --file-dir $DATA_PATH \
    --learning-rate .01 \
    --train-steps 1500 \
    --num-epochs 40 \
    --verbosity DEBUG

export MODEL_BINARIES=$OUTPUT_PATH/export_ckpt_1504
gcloud ml-engine versions create v7 --model isles_2017 --origin $MODEL_BINARIES --runtime-version 1.2


python -m tensorflow.tensorboard --logdir=$OUTPUT_PATH

python -m tensorflow.tensorboard --logdir=logs

gsutil cp isles2017.tfrecord gs://coral-weaver-4010/data



DATA_FORMAT=TF_RECORD
BUCKET_NAME=coral-weaver-4010
INPUT_PATHS=gs://$BUCKET_NAME/data/isles_tfrecords/*
INPUT_PATHS=gs://$BUCKET_NAME/data/testing_tfrecords/*
MODEL_NAME=isles_2017
REGION=us-east1
now=$(date +"%Y%m%d_%H%M%S")
JOB_NAME=isles_predict_$now
OUTPUT_PATH=gs://$BUCKET_NAME/$JOB_NAME/predictions
MAX_WORKER_COUNT=15

gcloud ml-engine jobs submit prediction $JOB_NAME \
    --model $MODEL_NAME \
    --input-paths $INPUT_PATHS \
    --output-path $OUTPUT_PATH \
    --region $REGION \
    --data-format $DATA_FORMAT \
    --max-worker-count=$MAX_WORKER_COUNT




gsutil cp $OUTPUT_PATH/* DataFiles/raw_testing_predictions/
gsutil cp gs://coral-weaver-4010/isles_predict_20170804_150716/predictions/* training_predictions/