#!/bin/bash

OUTPUT_PATH=logs
DATA_PATH=isles_tfrecords

gcloud ml-engine local train \
    --module-name trainer.task \
    --package-path trainer/ \
    --distributed \
    -- \
    --file-dir $DATA_PATH \
    --train-steps 20 \
    --num-epochs 1 \
    --learning-rate .01 \
    --job-dir $OUTPUT_PATH \
    --verbosity INFO



JOB_NAME=package_test_28
BUCKET_NAME=coral-weaver-4010
OUTPUT_PATH=gs://$BUCKET_NAME/$JOB_NAME
DATA_PATH=gs://$BUCKET_NAME/data/isles_tfrecords
REGION=us-east1

gcloud ml-engine jobs submit training $JOB_NAME \
    --job-dir $OUTPUT_PATH \
    --runtime-version 1.2 \
    --module-name trainer.task \
    --package-path trainer/ \
    --scale-tier CUSTOM \
    --config config_cheap.yaml \
    --region $REGION \
    -- \
    --file-dir $DATA_PATH \
    --learning-rate .01 \
    --train-steps 100 \
    --num-epochs 1 \
    --verbosity DEBUG



python -m tensorflow.tensorboard --logdir=$OUTPUT_PATH

python -m tensorflow.tensorboard --logdir=logs

gsutil cp isles2017.tfrecord gs://coral-weaver-4010/data

